### ISSUE TITLE
Group constraints

### ISSUE THREAD

**Issue by andrewrosemberg** [NREL-SIIP/PowerSimulations.jl#479]
Group constraints here simply denote constraints that bind several devices together, e.g. the sum of the reserves in a certain zone needs to be at least X. Some examples that we would need to consider would be:
* Minimum/maximum reserve allocation over a certain group of nodes, i.e., sum of the reserves of all generators in the group is bounded.
* Same as above for sum of multiple ancillary services, e.g., sum of total regulation up and up-spinning reserve in a certain group of nodes must be at least X.

**Comment by andrewrosemberg** [comment]
We believe that the following steps are necessary to add this feature:

1) Add a new service type with the appropriate fields on PSys:
* Create `mutable struct <name> <: Service`, constructors and parameter accessing functions (like in https://github.com/NREL-SIIP/PowerSystems.jl/blob/master/src/models/generated/AGC.jl).
* Verify if we need a new `add_service!` (https://github.com/NREL-SIIP/PowerSystems.jl/blob/master/src/models/devices.jl). Perhaps we need to make sure the related reserves were already added.

2) Add a formulation on PSim:
* Create appropriate formulation and `construct_service!` function (https://github.com/NREL-SIIP/PowerSimulations.jl/blob/dev0-6/src/services_models/services_constructor.jl). It has to check if the variables of the related services were already created.
* Create auxiliary functions to create the necessary variables and constraints (https://github.com/NREL-SIIP/PowerSimulations.jl/blob/dev0-6/src/services_models/agc.jl).

**Comment by raphaelsaavedra** [comment]
From what we discussed yesterday, interfaces would probably fall under the group constraint group.

(Interface in this case would simply be a single device that represents multiple lines through a set of weights.)

If you guys think we should open a separate issue about this, please let us know.
