### ISSUE TITLE
Certain functions should have an exclamation mark

### ISSUE THREAD

**Issue by raphaelsaavedra** [NREL-SIIP/PowerSimulations.jl#485]
I believe functions such as `device_semicontinuousrange` and `device_range` should probably be called `device_semicontinuousrange!` and `device_range!`, since they modify their first argument (`psi_container`) and don't return anything. The code is sometimes a little confusing because it looks like there's something missing.
If you agree with this I'll be happy to open a PR.

**Comment by jd-lara** [comment]
@raphaelsaavedra thanks, I will add this to #457 which should be merged as soon as the reviews are completed.
