### ISSUE TITLE
Improved Support for some Day-Ahead energy - services co-optimization 

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/PowerSimulations.jl#514]
The current design of devices and services doesn't support a straight forward way to make energy - services co-optimization problem. Several steps are required to support this in a straight forward way. I am opening this issue to keep track of the progress to get this going. 

- [x] New Cost Function structure  x-ref: https://github.com/NREL-SIIP/PowerSystems.jl/pull/596 
- [x] Refactor cost functions implementation x-ref: https://github.com/NREL-SIIP/PowerSimulations.jl/pull/516
- [x] Implement a system constructor finalizer call. 

cc. @andrewrosemberg @raphaelsaavedra

**Comment by andrewrosemberg** [comment]
should we remove the old wrong solution from PSY? https://github.com/NREL-SIIP/PowerSystems.jl/blob/e6bcc29f88d25ad5d7d61d4b893525651c6ee88e/src/models/generated/StaticReserve.jl#L35
I can make a PR for that.

**Comment by jd-lara** [comment]
@andrewrosemberg and @raphaelsaavedra, we have now support for market bids as requested originally. @sourabhdalvi has implemented examples of this. The last bullet point about the construction process will take a bit more to get done since we need to make changes to the problem build process.

**Comment by andrewrosemberg** [comment]
@jd-lara and @sourabhdalvi thanks for the effort and work done! This will help us a lot. Could you like the examples here?
