### ISSUE TITLE
Large case with PTDF stuck

### ISSUE THREAD

**Issue by andrewrosemberg** [NREL-SIIP/PowerSimulations.jl#525]
OperationsProblem of a Large case with PTDF gets stuck on building.

**Comment by jd-lara** [comment]
@andrewrosemberg can you test this again, please.

**Comment by andrewrosemberg** [comment]
will do!
can you reference also the PR where this was addressed here.

**Comment by jd-lara** [comment]
@andrewrosemberg please confirm this is ok. Otherwise, I will close the issue since we made changes to ensure the speed is acceptable.

**Comment by andrewrosemberg** [comment]
We have to update the code for the new versions to test this. The next project that will pick up where we left of will start soon (hopefully) and we will test if this is working.

**Comment by claytonpbarrows** [comment]
Note that we also enabled a new network formulation `PTDFPowerModel`. This formulation doesn't require calculation of the full PTDF matrix. It only calculates the shift factors for the branches that are represented with `StaticBranch` (i.e. flow limits are enforced). So, while it is less efficient in building constraints for each line, it avoids any variables and constraints for `StaticBranchUnbounded` branches and can be more efficient overall if you only care about flows on a relatively small number of branches.

**Comment by jd-lara** [comment]
@andrewrosemberg I will close this issue since now we made a lot of testing to make sure we can build large systems properly. There is room for improvement but the issue of "stuckedness" is resolved.

**Comment by andrewrosemberg** [comment]
Thank you for this! it will be essential for running the larger grids
