### ISSUE TITLE
Test creates duals but doesn't write any data for them

### ISSUE THREAD

**Issue by daniel-thom** [NREL-SIIP/PowerSimulations.jl#664]
Either this test is misconfigured or something is wrong with the code. Duals get created but are never written.

https://github.com/NREL-SIIP/PowerSimulations.jl/blob/master/test/test_simulation_results.jl#L420

**Comment by claytonpbarrows** [comment]
This behavior is expected, since this problem is a MIP and the duals are unavailable.
