### ISSUE TITLE
turbine_temperature error with fractional multistart time lags

### ISSUE THREAD

**Issue by kdayday** [NREL-SIIP/PowerSimulations.jl#677]
In co-opting turbine_temperature for my own code, I found a problem that likely also needs to be addressed there. I think turbine_temperature needs to account for the system's time interval to avoid indexing failures. For the TAMU day-ahead system, here's an error based on lines 768-770 in thermal_generation.jl:

```
g = "FAYETTE_POWER_U2_J1"
"FAYETTE_POWER_U2_J1"

julia> g_startup = get_start_time_limits(get_component(ThermalMultiStart, system, g))
(hot = 1.25, warm = 4.0, cold = 10.0)

julia> ix = 1
1

julia>             UnitRange{Int}(Int(g_startup[ix]), Int(g_startup[ix + 1] - 1))
ERROR: InexactError: Int64(1.25)
Stacktrace:
 [1] Int64(x::Float64)
   @ Base .\float.jl:723
 [2] top-level scope
   @ REPL[209]:1
```
For my own code, which has hourly resolution, I just threw a ```ceil``` around each ```Int``` argument.

**Comment by sourabhdalvi** [comment]
Hi Kate, The code does convert the startup data from hours to time periods using this function. https://github.com/NREL-SIIP/PowerSimulations.jl/blob/eae59fab1184a53354502c72af263144cc048138/src/devices_models/devices/thermal_generation.jl#L688-L698
https://github.com/NREL-SIIP/PowerSimulations.jl/blob/eae59fab1184a53354502c72af263144cc048138/src/devices_models/devices/thermal_generation.jl#L939
https://github.com/NREL-SIIP/PowerSimulations.jl/blob/eae59fab1184a53354502c72af263144cc048138/src/devices_models/devices/thermal_generation.jl#L1007
I also tried to replicate your error using this small example but I can't get it to replicate the same error.
```Julia 
using PowerSystemCaseBuilder
const PSB = PowerSystemCaseBuilder
sys = PSB.build_system(PSITestSystems, "c_sys5_pglib_sim")
set_start_time_limits!(get_component(ThermalGen, sys, "115_STEAM_1"), (hot = 2.125, warm = 4.0, cold = 12.0))

template = OperationsProblemTemplate(CopperPlatePowerModel)
set_device_model!(template, ThermalMultiStart, ThermalMultiStartUnitCommitment)
set_device_model!(template, RenewableDispatch, RenewableFullDispatch)
set_device_model!(template, PowerLoad, StaticPowerLoad)
set_device_model!(template, HydroDispatch, HydroDispatchRunOfRiver)

UC = OperationsProblem(
    template, 
    sys, 
    optimizer = solver, 
    optimizer_log_print = true,
)
build!(UC; serialize = false, output_dir = pwd())
solve!(UC)
```

**Comment by jd-lara** [comment]
@sourabhdalvi and @kdayday can you confirm the PSI versions you are using?

**Comment by sourabhdalvi** [comment]
> @sourabhdalvi and @kdayday can you confirm the PSI versions you are using?

PowerSimulations v0.14.1

**Comment by kdayday** [comment]
Looks like it's already taken care of, I didn't have that pre-processing in my copy/paste version.
