### ISSUE TITLE
LoadError: LoadError: UndefVarError: AbstractActivePowerFormulation not defined

### ISSUE THREAD

**Issue by csaiedu** [NREL-SIIP/PowerSimulations.jl#678]
When adding the PowerSimulations package after the PowerSystems package
I am getting the following error

LoadError: LoadError: UndefVarError: AbstractActivePowerFormulation not defined
'''
LoadError: LoadError: UndefVarError: AbstractActivePowerFormulation not defined

using Julia 1.6

[e690365d] PowerSimulations v0.14.1
[bcd98974] PowerSystems v1.4.2
[44cfe95a] Pkg

Thanks

**Comment by jd-lara** [comment]
@csaiedu can you share more of the backtrace please?

**Comment by csaiedu** [comment]
[ Info: Precompiling PowerSimulations [e690365d-45e2-57bb-ac84-44ba829e73c4]ERROR: LoadError: LoadError: UndefVarError: AbstractActivePowerFormulation not definedStacktrace:  [1] getproperty(x::Module, f::Symbol)    @ Base .\Base.jl:26  [2] top-level scope    @ ~\.julia\packages\PowerSimulations\5BrGH\src\network\network_models\networks.jl:1  [3] include(mod::Module, _path::String)    @ Base .\Base.jl:386  [4] include(x::String)    @ PowerSimulations ~\.julia\packages\PowerSimulations\5BrGH\src\PowerSimulations.jl:1  [5] top-level scope    @ ~\.julia\packages\PowerSimulations\5BrGH\src\PowerSimulations.jl:61  [6] include    @ .\Base.jl:386 [inlined]  [7] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)    @ Base .\loading.jl:1213  [8] top-level scope    @ none:1  [9] eval    @ .\boot.jl:360 [inlined] [10] eval(x::Expr)    @ Base.MainInclude .\client.jl:446 [11] top-level scope    @ none:1...\.julia\packages\PowerSimulations\5BrGH\src\network\network_models\networks.jl:1...\.julia\packages\PowerSimulations\5BrGH\src\PowerSimulations.jl:1 From: Jose Daniel LaraSent: 03 May 2021 18:25To: NREL-SIIP/PowerSimulations.jlCc: csaiedu; MentionSubject: Re: [NREL-SIIP/PowerSimulations.jl] LoadError: LoadError: UndefVarError: AbstractActivePowerFormulation not defined ***@***.*** can you share more of the backtrace please?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jd-lara** [comment]
Can you try to run `] up` I just tried to reproduce and I don't seem to be able to get the error.

**Comment by csaiedu** [comment]
I did and removed some dependencies from another package and it worked. Thanks
