### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/PowerSimulations.jl#721]
I am opening an issue to track the fact that we need to make the documentation for PowerSimulations.

**Comment by jd-lara** [comment]
List of items that need explicit documentation 

- [ ] Document the required interfaces for custom OperationModel types

**Comment by claytonpbarrows** [comment]
Formulation docs TODOs:

- [ ] how to describe expressions? e.g. which variables are added to the power balance expressions
- [ ] services
- [ ] slacks
- [ ] PWL cost equations
- [ ] Missing categories
  - [ ] Storage
  - [ ] Thermal
  - [ ] Hybrid
  - [ ] Branch
  - [ ] Network
  - [x] Renewable
  - [x] Hydro
  - [x] Load
