### ISSUE TITLE
"function" misspelled

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL-SIIP/PowerSimulations.jl#940]
https://github.com/NREL-SIIP/PowerSimulations.jl/blob/master/src/core/optimization_container.jl#L61
should be `get_objective_function`

**Comment by jd-lara** [comment]
fixed in [5254f40](https://github.com/NREL-SIIP/PowerSimulations.jl/pull/936/commits/5254f400ba561edc5ced6195e33d33cd8efb39cb)
