### ISSUE TITLE
Update DecisionModel to include "built_for_recurrent_solves"

### ISSUE THREAD

**Issue by alefcastelli** [NREL-SIIP/PowerSimulations.jl#941]
The key `built_for_recurrent_solves` is present in `OptimizationContainer`.
A function `built_for_recurrent_solves(container::OptimizationContainer)` is present in "optimization_container.jl"

Either a function to set the value of `built_for_recurrent_solves` or integrating this key in `DecisionModel` should be done to allow the user decide this.

**Comment by jd-lara** [comment]
The field `built_ for_recurrent_solves` is meant as an internal field to determine the construction process and it set given several combinations of other parameters. I won't be made public.
